/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as NeighborhoodsRouteImport } from './routes/neighborhoods'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as InsiderRouteImport } from './routes/insider'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIndexRouteImport } from './routes/listings.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as NeighborhoodsSlugRouteImport } from './routes/neighborhoods.$slug'
import { Route as ListingsSlugRouteImport } from './routes/listings.$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as AdminImpressionsRouteImport } from './routes/admin.impressions'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminListingsIndexRouteImport } from './routes/admin.listings.index'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin.articles.index'
import { Route as AdminListingsNewRouteImport } from './routes/admin.listings.new'
import { Route as AdminListingsIdRouteImport } from './routes/admin.listings.$id'
import { Route as AdminCmsSettingsRouteImport } from './routes/admin.cms.settings'
import { Route as AdminCmsNavigationRouteImport } from './routes/admin.cms.navigation'
import { Route as AdminCmsHomepageRouteImport } from './routes/admin.cms.homepage'
import { Route as AdminArticlesNewRouteImport } from './routes/admin.articles.new'
import { Route as AdminArticlesIdRouteImport } from './routes/admin.articles.$id'
import { Route as AdminCmsPagesIndexRouteImport } from './routes/admin.cms.pages.index'
import { Route as AdminCmsPagesIdRouteImport } from './routes/admin.cms.pages.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodsRoute = NeighborhoodsRouteImport.update({
  id: '/neighborhoods',
  path: '/neighborhoods',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const InsiderRoute = InsiderRouteImport.update({
  id: '/insider',
  path: '/insider',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListingsRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodsSlugRoute = NeighborhoodsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NeighborhoodsRoute,
} as any)
const ListingsSlugRoute = ListingsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ListingsRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminImpressionsRoute = AdminImpressionsRouteImport.update({
  id: '/impressions',
  path: '/impressions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsIndexRoute = AdminListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsNewRoute = AdminListingsNewRouteImport.update({
  id: '/listings/new',
  path: '/listings/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsIdRoute = AdminListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsSettingsRoute = AdminCmsSettingsRouteImport.update({
  id: '/cms/settings',
  path: '/cms/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsNavigationRoute = AdminCmsNavigationRouteImport.update({
  id: '/cms/navigation',
  path: '/cms/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsHomepageRoute = AdminCmsHomepageRouteImport.update({
  id: '/cms/homepage',
  path: '/cms/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesIdRoute = AdminArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsPagesIndexRoute = AdminCmsPagesIndexRouteImport.update({
  id: '/cms/pages/',
  path: '/cms/pages/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsPagesIdRoute = AdminCmsPagesIdRouteImport.update({
  id: '/cms/pages/$id',
  path: '/cms/pages/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/insider': typeof InsiderRoute
  '/listings': typeof ListingsRouteWithChildren
  '/neighborhoods': typeof NeighborhoodsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/impressions': typeof AdminImpressionsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/neighborhoods/$slug': typeof NeighborhoodsSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/cms/homepage': typeof AdminCmsHomepageRoute
  '/admin/cms/navigation': typeof AdminCmsNavigationRoute
  '/admin/cms/settings': typeof AdminCmsSettingsRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
  '/admin/cms/pages/$id': typeof AdminCmsPagesIdRoute
  '/admin/cms/pages/': typeof AdminCmsPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/insider': typeof InsiderRoute
  '/neighborhoods': typeof NeighborhoodsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/impressions': typeof AdminImpressionsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/neighborhoods/$slug': typeof NeighborhoodsSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/listings': typeof ListingsIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/cms/homepage': typeof AdminCmsHomepageRoute
  '/admin/cms/navigation': typeof AdminCmsNavigationRoute
  '/admin/cms/settings': typeof AdminCmsSettingsRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
  '/admin/listings': typeof AdminListingsIndexRoute
  '/admin/cms/pages/$id': typeof AdminCmsPagesIdRoute
  '/admin/cms/pages': typeof AdminCmsPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/insider': typeof InsiderRoute
  '/listings': typeof ListingsRouteWithChildren
  '/neighborhoods': typeof NeighborhoodsRouteWithChildren
  '/partners': typeof PartnersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/impressions': typeof AdminImpressionsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/neighborhoods/$slug': typeof NeighborhoodsSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/cms/homepage': typeof AdminCmsHomepageRoute
  '/admin/cms/navigation': typeof AdminCmsNavigationRoute
  '/admin/cms/settings': typeof AdminCmsSettingsRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
  '/admin/cms/pages/$id': typeof AdminCmsPagesIdRoute
  '/admin/cms/pages/': typeof AdminCmsPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/articles'
    | '/auth'
    | '/insider'
    | '/listings'
    | '/neighborhoods'
    | '/partners'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/import'
    | '/admin/impressions'
    | '/articles/$slug'
    | '/listings/$slug'
    | '/neighborhoods/$slug'
    | '/pages/$slug'
    | '/admin/'
    | '/articles/'
    | '/listings/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/cms/homepage'
    | '/admin/cms/navigation'
    | '/admin/cms/settings'
    | '/admin/listings/$id'
    | '/admin/listings/new'
    | '/admin/articles/'
    | '/admin/listings/'
    | '/admin/cms/pages/$id'
    | '/admin/cms/pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/insider'
    | '/neighborhoods'
    | '/partners'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/import'
    | '/admin/impressions'
    | '/articles/$slug'
    | '/listings/$slug'
    | '/neighborhoods/$slug'
    | '/pages/$slug'
    | '/admin'
    | '/articles'
    | '/listings'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/cms/homepage'
    | '/admin/cms/navigation'
    | '/admin/cms/settings'
    | '/admin/listings/$id'
    | '/admin/listings/new'
    | '/admin/articles'
    | '/admin/listings'
    | '/admin/cms/pages/$id'
    | '/admin/cms/pages'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/articles'
    | '/auth'
    | '/insider'
    | '/listings'
    | '/neighborhoods'
    | '/partners'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/import'
    | '/admin/impressions'
    | '/articles/$slug'
    | '/listings/$slug'
    | '/neighborhoods/$slug'
    | '/pages/$slug'
    | '/admin/'
    | '/articles/'
    | '/listings/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/cms/homepage'
    | '/admin/cms/navigation'
    | '/admin/cms/settings'
    | '/admin/listings/$id'
    | '/admin/listings/new'
    | '/admin/articles/'
    | '/admin/listings/'
    | '/admin/cms/pages/$id'
    | '/admin/cms/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArticlesRoute: typeof ArticlesRouteWithChildren
  AuthRoute: typeof AuthRoute
  InsiderRoute: typeof InsiderRoute
  ListingsRoute: typeof ListingsRouteWithChildren
  NeighborhoodsRoute: typeof NeighborhoodsRouteWithChildren
  PartnersRoute: typeof PartnersRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PagesSlugRoute: typeof PagesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhoods': {
      id: '/neighborhoods'
      path: '/neighborhoods'
      fullPath: '/neighborhoods'
      preLoaderRoute: typeof NeighborhoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insider': {
      id: '/insider'
      path: '/insider'
      fullPath: '/insider'
      preLoaderRoute: typeof InsiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhoods/$slug': {
      id: '/neighborhoods/$slug'
      path: '/$slug'
      fullPath: '/neighborhoods/$slug'
      preLoaderRoute: typeof NeighborhoodsSlugRouteImport
      parentRoute: typeof NeighborhoodsRoute
    }
    '/listings/$slug': {
      id: '/listings/$slug'
      path: '/$slug'
      fullPath: '/listings/$slug'
      preLoaderRoute: typeof ListingsSlugRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/impressions': {
      id: '/admin/impressions'
      path: '/impressions'
      fullPath: '/admin/impressions'
      preLoaderRoute: typeof AdminImpressionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings/': {
      id: '/admin/listings/'
      path: '/listings'
      fullPath: '/admin/listings/'
      preLoaderRoute: typeof AdminListingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings/new': {
      id: '/admin/listings/new'
      path: '/listings/new'
      fullPath: '/admin/listings/new'
      preLoaderRoute: typeof AdminListingsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings/$id': {
      id: '/admin/listings/$id'
      path: '/listings/$id'
      fullPath: '/admin/listings/$id'
      preLoaderRoute: typeof AdminListingsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/settings': {
      id: '/admin/cms/settings'
      path: '/cms/settings'
      fullPath: '/admin/cms/settings'
      preLoaderRoute: typeof AdminCmsSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/navigation': {
      id: '/admin/cms/navigation'
      path: '/cms/navigation'
      fullPath: '/admin/cms/navigation'
      preLoaderRoute: typeof AdminCmsNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/homepage': {
      id: '/admin/cms/homepage'
      path: '/cms/homepage'
      fullPath: '/admin/cms/homepage'
      preLoaderRoute: typeof AdminCmsHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/articles/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/$id': {
      id: '/admin/articles/$id'
      path: '/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AdminArticlesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/pages/': {
      id: '/admin/cms/pages/'
      path: '/cms/pages'
      fullPath: '/admin/cms/pages/'
      preLoaderRoute: typeof AdminCmsPagesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/pages/$id': {
      id: '/admin/cms/pages/$id'
      path: '/cms/pages/$id'
      fullPath: '/admin/cms/pages/$id'
      preLoaderRoute: typeof AdminCmsPagesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminImportRoute: typeof AdminImportRoute
  AdminImpressionsRoute: typeof AdminImpressionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArticlesIdRoute: typeof AdminArticlesIdRoute
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminCmsHomepageRoute: typeof AdminCmsHomepageRoute
  AdminCmsNavigationRoute: typeof AdminCmsNavigationRoute
  AdminCmsSettingsRoute: typeof AdminCmsSettingsRoute
  AdminListingsIdRoute: typeof AdminListingsIdRoute
  AdminListingsNewRoute: typeof AdminListingsNewRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
  AdminListingsIndexRoute: typeof AdminListingsIndexRoute
  AdminCmsPagesIdRoute: typeof AdminCmsPagesIdRoute
  AdminCmsPagesIndexRoute: typeof AdminCmsPagesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminImportRoute: AdminImportRoute,
  AdminImpressionsRoute: AdminImpressionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArticlesIdRoute: AdminArticlesIdRoute,
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminCmsHomepageRoute: AdminCmsHomepageRoute,
  AdminCmsNavigationRoute: AdminCmsNavigationRoute,
  AdminCmsSettingsRoute: AdminCmsSettingsRoute,
  AdminListingsIdRoute: AdminListingsIdRoute,
  AdminListingsNewRoute: AdminListingsNewRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
  AdminListingsIndexRoute: AdminListingsIndexRoute,
  AdminCmsPagesIdRoute: AdminCmsPagesIdRoute,
  AdminCmsPagesIndexRoute: AdminCmsPagesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface ListingsRouteChildren {
  ListingsSlugRoute: typeof ListingsSlugRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsSlugRoute: ListingsSlugRoute,
  ListingsIndexRoute: ListingsIndexRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

interface NeighborhoodsRouteChildren {
  NeighborhoodsSlugRoute: typeof NeighborhoodsSlugRoute
}

const NeighborhoodsRouteChildren: NeighborhoodsRouteChildren = {
  NeighborhoodsSlugRoute: NeighborhoodsSlugRoute,
}

const NeighborhoodsRouteWithChildren = NeighborhoodsRoute._addFileChildren(
  NeighborhoodsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArticlesRoute: ArticlesRouteWithChildren,
  AuthRoute: AuthRoute,
  InsiderRoute: InsiderRoute,
  ListingsRoute: ListingsRouteWithChildren,
  NeighborhoodsRoute: NeighborhoodsRouteWithChildren,
  PartnersRoute: PartnersRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PagesSlugRoute: PagesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
