/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapListingsDotxmlRouteImport } from './routes/sitemap-listings[.]xml'
import { Route as SitemapArticlesDotxmlRouteImport } from './routes/sitemap-articles[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as NeighborhoodsRouteImport } from './routes/neighborhoods'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as InsiderRouteImport } from './routes/insider'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WineriesIndexRouteImport } from './routes/wineries.index'
import { Route as WeddingsIndexRouteImport } from './routes/weddings.index'
import { Route as ThingsToDoIndexRouteImport } from './routes/things-to-do.index'
import { Route as ShoppingIndexRouteImport } from './routes/shopping.index'
import { Route as RestaurantsIndexRouteImport } from './routes/restaurants.index'
import { Route as NightlifeIndexRouteImport } from './routes/nightlife.index'
import { Route as ListingsIndexRouteImport } from './routes/listings.index'
import { Route as HotelsIndexRouteImport } from './routes/hotels.index'
import { Route as GolfCoursesIndexRouteImport } from './routes/golf-courses.index'
import { Route as CruisesIndexRouteImport } from './routes/cruises.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WineriesSlugRouteImport } from './routes/wineries.$slug'
import { Route as WeddingsSlugRouteImport } from './routes/weddings.$slug'
import { Route as ThingsToDoGolfRouteImport } from './routes/things-to-do.golf'
import { Route as ThingsToDoSlugRouteImport } from './routes/things-to-do.$slug'
import { Route as ShoppingSlugRouteImport } from './routes/shopping.$slug'
import { Route as SaveOnPillarRouteImport } from './routes/save-on.$pillar'
import { Route as RestaurantsSlugRouteImport } from './routes/restaurants.$slug'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as NightlifeSlugRouteImport } from './routes/nightlife.$slug'
import { Route as NeighborhoodsSlugRouteImport } from './routes/neighborhoods.$slug'
import { Route as ListingsSlugRouteImport } from './routes/listings.$slug'
import { Route as HotelsSlugRouteImport } from './routes/hotels.$slug'
import { Route as GolfCoursesSlugRouteImport } from './routes/golf-courses.$slug'
import { Route as CruisesSlugRouteImport } from './routes/cruises.$slug'
import { Route as ClaimSlugRouteImport } from './routes/claim.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthorsSlugRouteImport } from './routes/authors.$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminImpressionsRouteImport } from './routes/admin.impressions'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AdminClaimsRouteImport } from './routes/admin.claims'
import { Route as AdminApiKeysRouteImport } from './routes/admin.api-keys'
import { Route as AdminListingsIndexRouteImport } from './routes/admin.listings.index'
import { Route as AdminCruisesIndexRouteImport } from './routes/admin.cruises.index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin.articles.index'
import { Route as ApiPublicListingsRouteImport } from './routes/api/public/listings'
import { Route as ApiPublicBlogRouteImport } from './routes/api/public/blog'
import { Route as ApiPublicArticlesRouteImport } from './routes/api/public/articles'
import { Route as AdminListingsNewRouteImport } from './routes/admin.listings.new'
import { Route as AdminListingsIdRouteImport } from './routes/admin.listings.$id'
import { Route as AdminCruisesNewRouteImport } from './routes/admin.cruises.new'
import { Route as AdminCruisesIdRouteImport } from './routes/admin.cruises.$id'
import { Route as AdminCmsSettingsRouteImport } from './routes/admin.cms.settings'
import { Route as AdminCmsNavigationRouteImport } from './routes/admin.cms.navigation'
import { Route as AdminCmsHomepageRouteImport } from './routes/admin.cms.homepage'
import { Route as AdminCmsHomeNeighborhoodsRouteImport } from './routes/admin.cms.home-neighborhoods'
import { Route as AdminBlogNewRouteImport } from './routes/admin.blog.new'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'
import { Route as AdminArticlesNewRouteImport } from './routes/admin.articles.new'
import { Route as AdminArticlesIdRouteImport } from './routes/admin.articles.$id'
import { Route as CategoryInNeighborhoodRouteImport } from './routes/$category.in.$neighborhood'
import { Route as AdminCmsPagesIndexRouteImport } from './routes/admin.cms.pages.index'
import { Route as AdminCmsNeighborhoodsIndexRouteImport } from './routes/admin.cms.neighborhoods.index'
import { Route as AdminCmsPagesIdRouteImport } from './routes/admin.cms.pages.$id'
import { Route as AdminCmsNeighborhoodsIdRouteImport } from './routes/admin.cms.neighborhoods.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapListingsDotxmlRoute = SitemapListingsDotxmlRouteImport.update({
  id: '/sitemap-listings.xml',
  path: '/sitemap-listings.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapArticlesDotxmlRoute = SitemapArticlesDotxmlRouteImport.update({
  id: '/sitemap-articles.xml',
  path: '/sitemap-articles.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodsRoute = NeighborhoodsRouteImport.update({
  id: '/neighborhoods',
  path: '/neighborhoods',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const InsiderRoute = InsiderRouteImport.update({
  id: '/insider',
  path: '/insider',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WineriesIndexRoute = WineriesIndexRouteImport.update({
  id: '/wineries/',
  path: '/wineries/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingsIndexRoute = WeddingsIndexRouteImport.update({
  id: '/weddings/',
  path: '/weddings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThingsToDoIndexRoute = ThingsToDoIndexRouteImport.update({
  id: '/things-to-do/',
  path: '/things-to-do/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingIndexRoute = ShoppingIndexRouteImport.update({
  id: '/shopping/',
  path: '/shopping/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIndexRoute = RestaurantsIndexRouteImport.update({
  id: '/restaurants/',
  path: '/restaurants/',
  getParentRoute: () => rootRouteImport,
} as any)
const NightlifeIndexRoute = NightlifeIndexRouteImport.update({
  id: '/nightlife/',
  path: '/nightlife/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListingsRoute,
} as any)
const HotelsIndexRoute = HotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => rootRouteImport,
} as any)
const GolfCoursesIndexRoute = GolfCoursesIndexRouteImport.update({
  id: '/golf-courses/',
  path: '/golf-courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CruisesIndexRoute = CruisesIndexRouteImport.update({
  id: '/cruises/',
  path: '/cruises/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WineriesSlugRoute = WineriesSlugRouteImport.update({
  id: '/wineries/$slug',
  path: '/wineries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingsSlugRoute = WeddingsSlugRouteImport.update({
  id: '/weddings/$slug',
  path: '/weddings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ThingsToDoGolfRoute = ThingsToDoGolfRouteImport.update({
  id: '/things-to-do/golf',
  path: '/things-to-do/golf',
  getParentRoute: () => rootRouteImport,
} as any)
const ThingsToDoSlugRoute = ThingsToDoSlugRouteImport.update({
  id: '/things-to-do/$slug',
  path: '/things-to-do/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingSlugRoute = ShoppingSlugRouteImport.update({
  id: '/shopping/$slug',
  path: '/shopping/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SaveOnPillarRoute = SaveOnPillarRouteImport.update({
  id: '/save-on/$pillar',
  path: '/save-on/$pillar',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsSlugRoute = RestaurantsSlugRouteImport.update({
  id: '/restaurants/$slug',
  path: '/restaurants/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NightlifeSlugRoute = NightlifeSlugRouteImport.update({
  id: '/nightlife/$slug',
  path: '/nightlife/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodsSlugRoute = NeighborhoodsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NeighborhoodsRoute,
} as any)
const ListingsSlugRoute = ListingsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ListingsRoute,
} as any)
const HotelsSlugRoute = HotelsSlugRouteImport.update({
  id: '/hotels/$slug',
  path: '/hotels/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GolfCoursesSlugRoute = GolfCoursesSlugRouteImport.update({
  id: '/golf-courses/$slug',
  path: '/golf-courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CruisesSlugRoute = CruisesSlugRouteImport.update({
  id: '/cruises/$slug',
  path: '/cruises/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimSlugRoute = ClaimSlugRouteImport.update({
  id: '/claim/$slug',
  path: '/claim/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsSlugRoute = AuthorsSlugRouteImport.update({
  id: '/authors/$slug',
  path: '/authors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImpressionsRoute = AdminImpressionsRouteImport.update({
  id: '/impressions',
  path: '/impressions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClaimsRoute = AdminClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsIndexRoute = AdminListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCruisesIndexRoute = AdminCruisesIndexRouteImport.update({
  id: '/cruises/',
  path: '/cruises/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicListingsRoute = ApiPublicListingsRouteImport.update({
  id: '/api/public/listings',
  path: '/api/public/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBlogRoute = ApiPublicBlogRouteImport.update({
  id: '/api/public/blog',
  path: '/api/public/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArticlesRoute = ApiPublicArticlesRouteImport.update({
  id: '/api/public/articles',
  path: '/api/public/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminListingsNewRoute = AdminListingsNewRouteImport.update({
  id: '/listings/new',
  path: '/listings/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsIdRoute = AdminListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCruisesNewRoute = AdminCruisesNewRouteImport.update({
  id: '/cruises/new',
  path: '/cruises/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCruisesIdRoute = AdminCruisesIdRouteImport.update({
  id: '/cruises/$id',
  path: '/cruises/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsSettingsRoute = AdminCmsSettingsRouteImport.update({
  id: '/cms/settings',
  path: '/cms/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsNavigationRoute = AdminCmsNavigationRouteImport.update({
  id: '/cms/navigation',
  path: '/cms/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsHomepageRoute = AdminCmsHomepageRouteImport.update({
  id: '/cms/homepage',
  path: '/cms/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsHomeNeighborhoodsRoute =
  AdminCmsHomeNeighborhoodsRouteImport.update({
    id: '/cms/home-neighborhoods',
    path: '/cms/home-neighborhoods',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/blog/new',
  path: '/blog/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesIdRoute = AdminArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => AdminRoute,
} as any)
const CategoryInNeighborhoodRoute = CategoryInNeighborhoodRouteImport.update({
  id: '/$category/in/$neighborhood',
  path: '/$category/in/$neighborhood',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsPagesIndexRoute = AdminCmsPagesIndexRouteImport.update({
  id: '/cms/pages/',
  path: '/cms/pages/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsNeighborhoodsIndexRoute =
  AdminCmsNeighborhoodsIndexRouteImport.update({
    id: '/cms/neighborhoods/',
    path: '/cms/neighborhoods/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCmsPagesIdRoute = AdminCmsPagesIdRouteImport.update({
  id: '/cms/pages/$id',
  path: '/cms/pages/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsNeighborhoodsIdRoute = AdminCmsNeighborhoodsIdRouteImport.update({
  id: '/cms/neighborhoods/$id',
  path: '/cms/neighborhoods/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/insider': typeof InsiderRoute
  '/listings': typeof ListingsRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/neighborhoods': typeof NeighborhoodsRouteWithChildren
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-articles.xml': typeof SitemapArticlesDotxmlRoute
  '/sitemap-listings.xml': typeof SitemapListingsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/impressions': typeof AdminImpressionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/claim/$slug': typeof ClaimSlugRoute
  '/cruises/$slug': typeof CruisesSlugRoute
  '/golf-courses/$slug': typeof GolfCoursesSlugRoute
  '/hotels/$slug': typeof HotelsSlugRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/neighborhoods/$slug': typeof NeighborhoodsSlugRoute
  '/nightlife/$slug': typeof NightlifeSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/restaurants/$slug': typeof RestaurantsSlugRoute
  '/save-on/$pillar': typeof SaveOnPillarRoute
  '/shopping/$slug': typeof ShoppingSlugRoute
  '/things-to-do/$slug': typeof ThingsToDoSlugRoute
  '/things-to-do/golf': typeof ThingsToDoGolfRoute
  '/weddings/$slug': typeof WeddingsSlugRoute
  '/wineries/$slug': typeof WineriesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/cruises/': typeof CruisesIndexRoute
  '/golf-courses/': typeof GolfCoursesIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/nightlife/': typeof NightlifeIndexRoute
  '/restaurants/': typeof RestaurantsIndexRoute
  '/shopping/': typeof ShoppingIndexRoute
  '/things-to-do/': typeof ThingsToDoIndexRoute
  '/weddings/': typeof WeddingsIndexRoute
  '/wineries/': typeof WineriesIndexRoute
  '/$category/in/$neighborhood': typeof CategoryInNeighborhoodRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/cms/home-neighborhoods': typeof AdminCmsHomeNeighborhoodsRoute
  '/admin/cms/homepage': typeof AdminCmsHomepageRoute
  '/admin/cms/navigation': typeof AdminCmsNavigationRoute
  '/admin/cms/settings': typeof AdminCmsSettingsRoute
  '/admin/cruises/$id': typeof AdminCruisesIdRoute
  '/admin/cruises/new': typeof AdminCruisesNewRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/api/public/articles': typeof ApiPublicArticlesRoute
  '/api/public/blog': typeof ApiPublicBlogRoute
  '/api/public/listings': typeof ApiPublicListingsRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/cruises/': typeof AdminCruisesIndexRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
  '/admin/cms/neighborhoods/$id': typeof AdminCmsNeighborhoodsIdRoute
  '/admin/cms/pages/$id': typeof AdminCmsPagesIdRoute
  '/admin/cms/neighborhoods/': typeof AdminCmsNeighborhoodsIndexRoute
  '/admin/cms/pages/': typeof AdminCmsPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/insider': typeof InsiderRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/neighborhoods': typeof NeighborhoodsRouteWithChildren
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-articles.xml': typeof SitemapArticlesDotxmlRoute
  '/sitemap-listings.xml': typeof SitemapListingsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/impressions': typeof AdminImpressionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/claim/$slug': typeof ClaimSlugRoute
  '/cruises/$slug': typeof CruisesSlugRoute
  '/golf-courses/$slug': typeof GolfCoursesSlugRoute
  '/hotels/$slug': typeof HotelsSlugRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/neighborhoods/$slug': typeof NeighborhoodsSlugRoute
  '/nightlife/$slug': typeof NightlifeSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/restaurants/$slug': typeof RestaurantsSlugRoute
  '/save-on/$pillar': typeof SaveOnPillarRoute
  '/shopping/$slug': typeof ShoppingSlugRoute
  '/things-to-do/$slug': typeof ThingsToDoSlugRoute
  '/things-to-do/golf': typeof ThingsToDoGolfRoute
  '/weddings/$slug': typeof WeddingsSlugRoute
  '/wineries/$slug': typeof WineriesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/blog': typeof BlogIndexRoute
  '/cruises': typeof CruisesIndexRoute
  '/golf-courses': typeof GolfCoursesIndexRoute
  '/hotels': typeof HotelsIndexRoute
  '/listings': typeof ListingsIndexRoute
  '/nightlife': typeof NightlifeIndexRoute
  '/restaurants': typeof RestaurantsIndexRoute
  '/shopping': typeof ShoppingIndexRoute
  '/things-to-do': typeof ThingsToDoIndexRoute
  '/weddings': typeof WeddingsIndexRoute
  '/wineries': typeof WineriesIndexRoute
  '/$category/in/$neighborhood': typeof CategoryInNeighborhoodRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/cms/home-neighborhoods': typeof AdminCmsHomeNeighborhoodsRoute
  '/admin/cms/homepage': typeof AdminCmsHomepageRoute
  '/admin/cms/navigation': typeof AdminCmsNavigationRoute
  '/admin/cms/settings': typeof AdminCmsSettingsRoute
  '/admin/cruises/$id': typeof AdminCruisesIdRoute
  '/admin/cruises/new': typeof AdminCruisesNewRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/api/public/articles': typeof ApiPublicArticlesRoute
  '/api/public/blog': typeof ApiPublicBlogRoute
  '/api/public/listings': typeof ApiPublicListingsRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/cruises': typeof AdminCruisesIndexRoute
  '/admin/listings': typeof AdminListingsIndexRoute
  '/admin/cms/neighborhoods/$id': typeof AdminCmsNeighborhoodsIdRoute
  '/admin/cms/pages/$id': typeof AdminCmsPagesIdRoute
  '/admin/cms/neighborhoods': typeof AdminCmsNeighborhoodsIndexRoute
  '/admin/cms/pages': typeof AdminCmsPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/insider': typeof InsiderRoute
  '/listings': typeof ListingsRouteWithChildren
  '/llms.txt': typeof LlmsDottxtRoute
  '/neighborhoods': typeof NeighborhoodsRouteWithChildren
  '/partner': typeof PartnerRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap-articles.xml': typeof SitemapArticlesDotxmlRoute
  '/sitemap-listings.xml': typeof SitemapListingsDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/claims': typeof AdminClaimsRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/impressions': typeof AdminImpressionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/authors/$slug': typeof AuthorsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/claim/$slug': typeof ClaimSlugRoute
  '/cruises/$slug': typeof CruisesSlugRoute
  '/golf-courses/$slug': typeof GolfCoursesSlugRoute
  '/hotels/$slug': typeof HotelsSlugRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/neighborhoods/$slug': typeof NeighborhoodsSlugRoute
  '/nightlife/$slug': typeof NightlifeSlugRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/restaurants/$slug': typeof RestaurantsSlugRoute
  '/save-on/$pillar': typeof SaveOnPillarRoute
  '/shopping/$slug': typeof ShoppingSlugRoute
  '/things-to-do/$slug': typeof ThingsToDoSlugRoute
  '/things-to-do/golf': typeof ThingsToDoGolfRoute
  '/weddings/$slug': typeof WeddingsSlugRoute
  '/wineries/$slug': typeof WineriesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/cruises/': typeof CruisesIndexRoute
  '/golf-courses/': typeof GolfCoursesIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/nightlife/': typeof NightlifeIndexRoute
  '/restaurants/': typeof RestaurantsIndexRoute
  '/shopping/': typeof ShoppingIndexRoute
  '/things-to-do/': typeof ThingsToDoIndexRoute
  '/weddings/': typeof WeddingsIndexRoute
  '/wineries/': typeof WineriesIndexRoute
  '/$category/in/$neighborhood': typeof CategoryInNeighborhoodRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/cms/home-neighborhoods': typeof AdminCmsHomeNeighborhoodsRoute
  '/admin/cms/homepage': typeof AdminCmsHomepageRoute
  '/admin/cms/navigation': typeof AdminCmsNavigationRoute
  '/admin/cms/settings': typeof AdminCmsSettingsRoute
  '/admin/cruises/$id': typeof AdminCruisesIdRoute
  '/admin/cruises/new': typeof AdminCruisesNewRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/api/public/articles': typeof ApiPublicArticlesRoute
  '/api/public/blog': typeof ApiPublicBlogRoute
  '/api/public/listings': typeof ApiPublicListingsRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/cruises/': typeof AdminCruisesIndexRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
  '/admin/cms/neighborhoods/$id': typeof AdminCmsNeighborhoodsIdRoute
  '/admin/cms/pages/$id': typeof AdminCmsPagesIdRoute
  '/admin/cms/neighborhoods/': typeof AdminCmsNeighborhoodsIndexRoute
  '/admin/cms/pages/': typeof AdminCmsPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/auth'
    | '/contact'
    | '/insider'
    | '/listings'
    | '/llms.txt'
    | '/neighborhoods'
    | '/partner'
    | '/partners'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap-articles.xml'
    | '/sitemap-listings.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/api-keys'
    | '/admin/claims'
    | '/admin/import'
    | '/admin/impressions'
    | '/admin/users'
    | '/articles/$slug'
    | '/authors/$slug'
    | '/blog/$slug'
    | '/claim/$slug'
    | '/cruises/$slug'
    | '/golf-courses/$slug'
    | '/hotels/$slug'
    | '/listings/$slug'
    | '/neighborhoods/$slug'
    | '/nightlife/$slug'
    | '/pages/$slug'
    | '/restaurants/$slug'
    | '/save-on/$pillar'
    | '/shopping/$slug'
    | '/things-to-do/$slug'
    | '/things-to-do/golf'
    | '/weddings/$slug'
    | '/wineries/$slug'
    | '/admin/'
    | '/articles/'
    | '/blog/'
    | '/cruises/'
    | '/golf-courses/'
    | '/hotels/'
    | '/listings/'
    | '/nightlife/'
    | '/restaurants/'
    | '/shopping/'
    | '/things-to-do/'
    | '/weddings/'
    | '/wineries/'
    | '/$category/in/$neighborhood'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/cms/home-neighborhoods'
    | '/admin/cms/homepage'
    | '/admin/cms/navigation'
    | '/admin/cms/settings'
    | '/admin/cruises/$id'
    | '/admin/cruises/new'
    | '/admin/listings/$id'
    | '/admin/listings/new'
    | '/api/public/articles'
    | '/api/public/blog'
    | '/api/public/listings'
    | '/admin/articles/'
    | '/admin/blog/'
    | '/admin/cruises/'
    | '/admin/listings/'
    | '/admin/cms/neighborhoods/$id'
    | '/admin/cms/pages/$id'
    | '/admin/cms/neighborhoods/'
    | '/admin/cms/pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/insider'
    | '/llms.txt'
    | '/neighborhoods'
    | '/partner'
    | '/partners'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap-articles.xml'
    | '/sitemap-listings.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/api-keys'
    | '/admin/claims'
    | '/admin/import'
    | '/admin/impressions'
    | '/admin/users'
    | '/articles/$slug'
    | '/authors/$slug'
    | '/blog/$slug'
    | '/claim/$slug'
    | '/cruises/$slug'
    | '/golf-courses/$slug'
    | '/hotels/$slug'
    | '/listings/$slug'
    | '/neighborhoods/$slug'
    | '/nightlife/$slug'
    | '/pages/$slug'
    | '/restaurants/$slug'
    | '/save-on/$pillar'
    | '/shopping/$slug'
    | '/things-to-do/$slug'
    | '/things-to-do/golf'
    | '/weddings/$slug'
    | '/wineries/$slug'
    | '/admin'
    | '/articles'
    | '/blog'
    | '/cruises'
    | '/golf-courses'
    | '/hotels'
    | '/listings'
    | '/nightlife'
    | '/restaurants'
    | '/shopping'
    | '/things-to-do'
    | '/weddings'
    | '/wineries'
    | '/$category/in/$neighborhood'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/cms/home-neighborhoods'
    | '/admin/cms/homepage'
    | '/admin/cms/navigation'
    | '/admin/cms/settings'
    | '/admin/cruises/$id'
    | '/admin/cruises/new'
    | '/admin/listings/$id'
    | '/admin/listings/new'
    | '/api/public/articles'
    | '/api/public/blog'
    | '/api/public/listings'
    | '/admin/articles'
    | '/admin/blog'
    | '/admin/cruises'
    | '/admin/listings'
    | '/admin/cms/neighborhoods/$id'
    | '/admin/cms/pages/$id'
    | '/admin/cms/neighborhoods'
    | '/admin/cms/pages'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/auth'
    | '/contact'
    | '/insider'
    | '/listings'
    | '/llms.txt'
    | '/neighborhoods'
    | '/partner'
    | '/partners'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap-articles.xml'
    | '/sitemap-listings.xml'
    | '/sitemap-pages.xml'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/api-keys'
    | '/admin/claims'
    | '/admin/import'
    | '/admin/impressions'
    | '/admin/users'
    | '/articles/$slug'
    | '/authors/$slug'
    | '/blog/$slug'
    | '/claim/$slug'
    | '/cruises/$slug'
    | '/golf-courses/$slug'
    | '/hotels/$slug'
    | '/listings/$slug'
    | '/neighborhoods/$slug'
    | '/nightlife/$slug'
    | '/pages/$slug'
    | '/restaurants/$slug'
    | '/save-on/$pillar'
    | '/shopping/$slug'
    | '/things-to-do/$slug'
    | '/things-to-do/golf'
    | '/weddings/$slug'
    | '/wineries/$slug'
    | '/admin/'
    | '/articles/'
    | '/blog/'
    | '/cruises/'
    | '/golf-courses/'
    | '/hotels/'
    | '/listings/'
    | '/nightlife/'
    | '/restaurants/'
    | '/shopping/'
    | '/things-to-do/'
    | '/weddings/'
    | '/wineries/'
    | '/$category/in/$neighborhood'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/cms/home-neighborhoods'
    | '/admin/cms/homepage'
    | '/admin/cms/navigation'
    | '/admin/cms/settings'
    | '/admin/cruises/$id'
    | '/admin/cruises/new'
    | '/admin/listings/$id'
    | '/admin/listings/new'
    | '/api/public/articles'
    | '/api/public/blog'
    | '/api/public/listings'
    | '/admin/articles/'
    | '/admin/blog/'
    | '/admin/cruises/'
    | '/admin/listings/'
    | '/admin/cms/neighborhoods/$id'
    | '/admin/cms/pages/$id'
    | '/admin/cms/neighborhoods/'
    | '/admin/cms/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArticlesRoute: typeof ArticlesRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  InsiderRoute: typeof InsiderRoute
  ListingsRoute: typeof ListingsRouteWithChildren
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  NeighborhoodsRoute: typeof NeighborhoodsRouteWithChildren
  PartnerRoute: typeof PartnerRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapArticlesDotxmlRoute: typeof SitemapArticlesDotxmlRoute
  SitemapListingsDotxmlRoute: typeof SitemapListingsDotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AuthorsSlugRoute: typeof AuthorsSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ClaimSlugRoute: typeof ClaimSlugRoute
  CruisesSlugRoute: typeof CruisesSlugRoute
  GolfCoursesSlugRoute: typeof GolfCoursesSlugRoute
  HotelsSlugRoute: typeof HotelsSlugRoute
  NightlifeSlugRoute: typeof NightlifeSlugRoute
  PagesSlugRoute: typeof PagesSlugRoute
  RestaurantsSlugRoute: typeof RestaurantsSlugRoute
  SaveOnPillarRoute: typeof SaveOnPillarRoute
  ShoppingSlugRoute: typeof ShoppingSlugRoute
  ThingsToDoSlugRoute: typeof ThingsToDoSlugRoute
  ThingsToDoGolfRoute: typeof ThingsToDoGolfRoute
  WeddingsSlugRoute: typeof WeddingsSlugRoute
  WineriesSlugRoute: typeof WineriesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CruisesIndexRoute: typeof CruisesIndexRoute
  GolfCoursesIndexRoute: typeof GolfCoursesIndexRoute
  HotelsIndexRoute: typeof HotelsIndexRoute
  NightlifeIndexRoute: typeof NightlifeIndexRoute
  RestaurantsIndexRoute: typeof RestaurantsIndexRoute
  ShoppingIndexRoute: typeof ShoppingIndexRoute
  ThingsToDoIndexRoute: typeof ThingsToDoIndexRoute
  WeddingsIndexRoute: typeof WeddingsIndexRoute
  WineriesIndexRoute: typeof WineriesIndexRoute
  CategoryInNeighborhoodRoute: typeof CategoryInNeighborhoodRoute
  ApiPublicArticlesRoute: typeof ApiPublicArticlesRoute
  ApiPublicBlogRoute: typeof ApiPublicBlogRoute
  ApiPublicListingsRoute: typeof ApiPublicListingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-listings.xml': {
      id: '/sitemap-listings.xml'
      path: '/sitemap-listings.xml'
      fullPath: '/sitemap-listings.xml'
      preLoaderRoute: typeof SitemapListingsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-articles.xml': {
      id: '/sitemap-articles.xml'
      path: '/sitemap-articles.xml'
      fullPath: '/sitemap-articles.xml'
      preLoaderRoute: typeof SitemapArticlesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhoods': {
      id: '/neighborhoods'
      path: '/neighborhoods'
      fullPath: '/neighborhoods'
      preLoaderRoute: typeof NeighborhoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insider': {
      id: '/insider'
      path: '/insider'
      fullPath: '/insider'
      preLoaderRoute: typeof InsiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wineries/': {
      id: '/wineries/'
      path: '/wineries'
      fullPath: '/wineries/'
      preLoaderRoute: typeof WineriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weddings/': {
      id: '/weddings/'
      path: '/weddings'
      fullPath: '/weddings/'
      preLoaderRoute: typeof WeddingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/things-to-do/': {
      id: '/things-to-do/'
      path: '/things-to-do'
      fullPath: '/things-to-do/'
      preLoaderRoute: typeof ThingsToDoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping/': {
      id: '/shopping/'
      path: '/shopping'
      fullPath: '/shopping/'
      preLoaderRoute: typeof ShoppingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/': {
      id: '/restaurants/'
      path: '/restaurants'
      fullPath: '/restaurants/'
      preLoaderRoute: typeof RestaurantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nightlife/': {
      id: '/nightlife/'
      path: '/nightlife'
      fullPath: '/nightlife/'
      preLoaderRoute: typeof NightlifeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/hotels/': {
      id: '/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof HotelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golf-courses/': {
      id: '/golf-courses/'
      path: '/golf-courses'
      fullPath: '/golf-courses/'
      preLoaderRoute: typeof GolfCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruises/': {
      id: '/cruises/'
      path: '/cruises'
      fullPath: '/cruises/'
      preLoaderRoute: typeof CruisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wineries/$slug': {
      id: '/wineries/$slug'
      path: '/wineries/$slug'
      fullPath: '/wineries/$slug'
      preLoaderRoute: typeof WineriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weddings/$slug': {
      id: '/weddings/$slug'
      path: '/weddings/$slug'
      fullPath: '/weddings/$slug'
      preLoaderRoute: typeof WeddingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/things-to-do/golf': {
      id: '/things-to-do/golf'
      path: '/things-to-do/golf'
      fullPath: '/things-to-do/golf'
      preLoaderRoute: typeof ThingsToDoGolfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/things-to-do/$slug': {
      id: '/things-to-do/$slug'
      path: '/things-to-do/$slug'
      fullPath: '/things-to-do/$slug'
      preLoaderRoute: typeof ThingsToDoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping/$slug': {
      id: '/shopping/$slug'
      path: '/shopping/$slug'
      fullPath: '/shopping/$slug'
      preLoaderRoute: typeof ShoppingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/save-on/$pillar': {
      id: '/save-on/$pillar'
      path: '/save-on/$pillar'
      fullPath: '/save-on/$pillar'
      preLoaderRoute: typeof SaveOnPillarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$slug': {
      id: '/restaurants/$slug'
      path: '/restaurants/$slug'
      fullPath: '/restaurants/$slug'
      preLoaderRoute: typeof RestaurantsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nightlife/$slug': {
      id: '/nightlife/$slug'
      path: '/nightlife/$slug'
      fullPath: '/nightlife/$slug'
      preLoaderRoute: typeof NightlifeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhoods/$slug': {
      id: '/neighborhoods/$slug'
      path: '/$slug'
      fullPath: '/neighborhoods/$slug'
      preLoaderRoute: typeof NeighborhoodsSlugRouteImport
      parentRoute: typeof NeighborhoodsRoute
    }
    '/listings/$slug': {
      id: '/listings/$slug'
      path: '/$slug'
      fullPath: '/listings/$slug'
      preLoaderRoute: typeof ListingsSlugRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/hotels/$slug': {
      id: '/hotels/$slug'
      path: '/hotels/$slug'
      fullPath: '/hotels/$slug'
      preLoaderRoute: typeof HotelsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/golf-courses/$slug': {
      id: '/golf-courses/$slug'
      path: '/golf-courses/$slug'
      fullPath: '/golf-courses/$slug'
      preLoaderRoute: typeof GolfCoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cruises/$slug': {
      id: '/cruises/$slug'
      path: '/cruises/$slug'
      fullPath: '/cruises/$slug'
      preLoaderRoute: typeof CruisesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$slug': {
      id: '/claim/$slug'
      path: '/claim/$slug'
      fullPath: '/claim/$slug'
      preLoaderRoute: typeof ClaimSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$slug': {
      id: '/authors/$slug'
      path: '/authors/$slug'
      fullPath: '/authors/$slug'
      preLoaderRoute: typeof AuthorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/impressions': {
      id: '/admin/impressions'
      path: '/impressions'
      fullPath: '/admin/impressions'
      preLoaderRoute: typeof AdminImpressionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/claims': {
      id: '/admin/claims'
      path: '/claims'
      fullPath: '/admin/claims'
      preLoaderRoute: typeof AdminClaimsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings/': {
      id: '/admin/listings/'
      path: '/listings'
      fullPath: '/admin/listings/'
      preLoaderRoute: typeof AdminListingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cruises/': {
      id: '/admin/cruises/'
      path: '/cruises'
      fullPath: '/admin/cruises/'
      preLoaderRoute: typeof AdminCruisesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/listings': {
      id: '/api/public/listings'
      path: '/api/public/listings'
      fullPath: '/api/public/listings'
      preLoaderRoute: typeof ApiPublicListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/blog': {
      id: '/api/public/blog'
      path: '/api/public/blog'
      fullPath: '/api/public/blog'
      preLoaderRoute: typeof ApiPublicBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/articles': {
      id: '/api/public/articles'
      path: '/api/public/articles'
      fullPath: '/api/public/articles'
      preLoaderRoute: typeof ApiPublicArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/listings/new': {
      id: '/admin/listings/new'
      path: '/listings/new'
      fullPath: '/admin/listings/new'
      preLoaderRoute: typeof AdminListingsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings/$id': {
      id: '/admin/listings/$id'
      path: '/listings/$id'
      fullPath: '/admin/listings/$id'
      preLoaderRoute: typeof AdminListingsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cruises/new': {
      id: '/admin/cruises/new'
      path: '/cruises/new'
      fullPath: '/admin/cruises/new'
      preLoaderRoute: typeof AdminCruisesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cruises/$id': {
      id: '/admin/cruises/$id'
      path: '/cruises/$id'
      fullPath: '/admin/cruises/$id'
      preLoaderRoute: typeof AdminCruisesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/settings': {
      id: '/admin/cms/settings'
      path: '/cms/settings'
      fullPath: '/admin/cms/settings'
      preLoaderRoute: typeof AdminCmsSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/navigation': {
      id: '/admin/cms/navigation'
      path: '/cms/navigation'
      fullPath: '/admin/cms/navigation'
      preLoaderRoute: typeof AdminCmsNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/homepage': {
      id: '/admin/cms/homepage'
      path: '/cms/homepage'
      fullPath: '/admin/cms/homepage'
      preLoaderRoute: typeof AdminCmsHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/home-neighborhoods': {
      id: '/admin/cms/home-neighborhoods'
      path: '/cms/home-neighborhoods'
      fullPath: '/admin/cms/home-neighborhoods'
      preLoaderRoute: typeof AdminCmsHomeNeighborhoodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/articles/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/$id': {
      id: '/admin/articles/$id'
      path: '/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AdminArticlesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$category/in/$neighborhood': {
      id: '/$category/in/$neighborhood'
      path: '/$category/in/$neighborhood'
      fullPath: '/$category/in/$neighborhood'
      preLoaderRoute: typeof CategoryInNeighborhoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cms/pages/': {
      id: '/admin/cms/pages/'
      path: '/cms/pages'
      fullPath: '/admin/cms/pages/'
      preLoaderRoute: typeof AdminCmsPagesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/neighborhoods/': {
      id: '/admin/cms/neighborhoods/'
      path: '/cms/neighborhoods'
      fullPath: '/admin/cms/neighborhoods/'
      preLoaderRoute: typeof AdminCmsNeighborhoodsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/pages/$id': {
      id: '/admin/cms/pages/$id'
      path: '/cms/pages/$id'
      fullPath: '/admin/cms/pages/$id'
      preLoaderRoute: typeof AdminCmsPagesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/neighborhoods/$id': {
      id: '/admin/cms/neighborhoods/$id'
      path: '/cms/neighborhoods/$id'
      fullPath: '/admin/cms/neighborhoods/$id'
      preLoaderRoute: typeof AdminCmsNeighborhoodsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminClaimsRoute: typeof AdminClaimsRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminImpressionsRoute: typeof AdminImpressionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArticlesIdRoute: typeof AdminArticlesIdRoute
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminCmsHomeNeighborhoodsRoute: typeof AdminCmsHomeNeighborhoodsRoute
  AdminCmsHomepageRoute: typeof AdminCmsHomepageRoute
  AdminCmsNavigationRoute: typeof AdminCmsNavigationRoute
  AdminCmsSettingsRoute: typeof AdminCmsSettingsRoute
  AdminCruisesIdRoute: typeof AdminCruisesIdRoute
  AdminCruisesNewRoute: typeof AdminCruisesNewRoute
  AdminListingsIdRoute: typeof AdminListingsIdRoute
  AdminListingsNewRoute: typeof AdminListingsNewRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminCruisesIndexRoute: typeof AdminCruisesIndexRoute
  AdminListingsIndexRoute: typeof AdminListingsIndexRoute
  AdminCmsNeighborhoodsIdRoute: typeof AdminCmsNeighborhoodsIdRoute
  AdminCmsPagesIdRoute: typeof AdminCmsPagesIdRoute
  AdminCmsNeighborhoodsIndexRoute: typeof AdminCmsNeighborhoodsIndexRoute
  AdminCmsPagesIndexRoute: typeof AdminCmsPagesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminClaimsRoute: AdminClaimsRoute,
  AdminImportRoute: AdminImportRoute,
  AdminImpressionsRoute: AdminImpressionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArticlesIdRoute: AdminArticlesIdRoute,
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminCmsHomeNeighborhoodsRoute: AdminCmsHomeNeighborhoodsRoute,
  AdminCmsHomepageRoute: AdminCmsHomepageRoute,
  AdminCmsNavigationRoute: AdminCmsNavigationRoute,
  AdminCmsSettingsRoute: AdminCmsSettingsRoute,
  AdminCruisesIdRoute: AdminCruisesIdRoute,
  AdminCruisesNewRoute: AdminCruisesNewRoute,
  AdminListingsIdRoute: AdminListingsIdRoute,
  AdminListingsNewRoute: AdminListingsNewRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminCruisesIndexRoute: AdminCruisesIndexRoute,
  AdminListingsIndexRoute: AdminListingsIndexRoute,
  AdminCmsNeighborhoodsIdRoute: AdminCmsNeighborhoodsIdRoute,
  AdminCmsPagesIdRoute: AdminCmsPagesIdRoute,
  AdminCmsNeighborhoodsIndexRoute: AdminCmsNeighborhoodsIndexRoute,
  AdminCmsPagesIndexRoute: AdminCmsPagesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface ListingsRouteChildren {
  ListingsSlugRoute: typeof ListingsSlugRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsSlugRoute: ListingsSlugRoute,
  ListingsIndexRoute: ListingsIndexRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

interface NeighborhoodsRouteChildren {
  NeighborhoodsSlugRoute: typeof NeighborhoodsSlugRoute
}

const NeighborhoodsRouteChildren: NeighborhoodsRouteChildren = {
  NeighborhoodsSlugRoute: NeighborhoodsSlugRoute,
}

const NeighborhoodsRouteWithChildren = NeighborhoodsRoute._addFileChildren(
  NeighborhoodsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ArticlesRoute: ArticlesRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  InsiderRoute: InsiderRoute,
  ListingsRoute: ListingsRouteWithChildren,
  LlmsDottxtRoute: LlmsDottxtRoute,
  NeighborhoodsRoute: NeighborhoodsRouteWithChildren,
  PartnerRoute: PartnerRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapArticlesDotxmlRoute: SitemapArticlesDotxmlRoute,
  SitemapListingsDotxmlRoute: SitemapListingsDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AuthorsSlugRoute: AuthorsSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  ClaimSlugRoute: ClaimSlugRoute,
  CruisesSlugRoute: CruisesSlugRoute,
  GolfCoursesSlugRoute: GolfCoursesSlugRoute,
  HotelsSlugRoute: HotelsSlugRoute,
  NightlifeSlugRoute: NightlifeSlugRoute,
  PagesSlugRoute: PagesSlugRoute,
  RestaurantsSlugRoute: RestaurantsSlugRoute,
  SaveOnPillarRoute: SaveOnPillarRoute,
  ShoppingSlugRoute: ShoppingSlugRoute,
  ThingsToDoSlugRoute: ThingsToDoSlugRoute,
  ThingsToDoGolfRoute: ThingsToDoGolfRoute,
  WeddingsSlugRoute: WeddingsSlugRoute,
  WineriesSlugRoute: WineriesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CruisesIndexRoute: CruisesIndexRoute,
  GolfCoursesIndexRoute: GolfCoursesIndexRoute,
  HotelsIndexRoute: HotelsIndexRoute,
  NightlifeIndexRoute: NightlifeIndexRoute,
  RestaurantsIndexRoute: RestaurantsIndexRoute,
  ShoppingIndexRoute: ShoppingIndexRoute,
  ThingsToDoIndexRoute: ThingsToDoIndexRoute,
  WeddingsIndexRoute: WeddingsIndexRoute,
  WineriesIndexRoute: WineriesIndexRoute,
  CategoryInNeighborhoodRoute: CategoryInNeighborhoodRoute,
  ApiPublicArticlesRoute: ApiPublicArticlesRoute,
  ApiPublicBlogRoute: ApiPublicBlogRoute,
  ApiPublicListingsRoute: ApiPublicListingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
