/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as NeighborhoodsRouteImport } from './routes/neighborhoods'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ListingsSlugRouteImport } from './routes/listings.$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as AdminImpressionsRouteImport } from './routes/admin.impressions'
import { Route as AdminListingsIndexRouteImport } from './routes/admin.listings.index'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin.articles.index'
import { Route as AdminListingsNewRouteImport } from './routes/admin.listings.new'
import { Route as AdminListingsIdRouteImport } from './routes/admin.listings.$id'
import { Route as AdminArticlesNewRouteImport } from './routes/admin.articles.new'
import { Route as AdminArticlesIdRouteImport } from './routes/admin.articles.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodsRoute = NeighborhoodsRouteImport.update({
  id: '/neighborhoods',
  path: '/neighborhoods',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ListingsSlugRoute = ListingsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ListingsRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminImpressionsRoute = AdminImpressionsRouteImport.update({
  id: '/impressions',
  path: '/impressions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsIndexRoute = AdminListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsNewRoute = AdminListingsNewRouteImport.update({
  id: '/listings/new',
  path: '/listings/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsIdRoute = AdminListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesIdRoute = AdminArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/listings': typeof ListingsRouteWithChildren
  '/neighborhoods': typeof NeighborhoodsRoute
  '/partners': typeof PartnersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/impressions': typeof AdminImpressionsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/listings': typeof ListingsRouteWithChildren
  '/neighborhoods': typeof NeighborhoodsRoute
  '/partners': typeof PartnersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/impressions': typeof AdminImpressionsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
  '/admin/listings': typeof AdminListingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/auth': typeof AuthRoute
  '/listings': typeof ListingsRouteWithChildren
  '/neighborhoods': typeof NeighborhoodsRoute
  '/partners': typeof PartnersRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/impressions': typeof AdminImpressionsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/listings/$slug': typeof ListingsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/listings/$id': typeof AdminListingsIdRoute
  '/admin/listings/new': typeof AdminListingsNewRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/listings/': typeof AdminListingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/articles'
    | '/auth'
    | '/listings'
    | '/neighborhoods'
    | '/partners'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/impressions'
    | '/articles/$slug'
    | '/listings/$slug'
    | '/admin/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/listings/$id'
    | '/admin/listings/new'
    | '/admin/articles/'
    | '/admin/listings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/articles'
    | '/auth'
    | '/listings'
    | '/neighborhoods'
    | '/partners'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/impressions'
    | '/articles/$slug'
    | '/listings/$slug'
    | '/admin'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/listings/$id'
    | '/admin/listings/new'
    | '/admin/articles'
    | '/admin/listings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/articles'
    | '/auth'
    | '/listings'
    | '/neighborhoods'
    | '/partners'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/impressions'
    | '/articles/$slug'
    | '/listings/$slug'
    | '/admin/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/listings/$id'
    | '/admin/listings/new'
    | '/admin/articles/'
    | '/admin/listings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArticlesRoute: typeof ArticlesRouteWithChildren
  AuthRoute: typeof AuthRoute
  ListingsRoute: typeof ListingsRouteWithChildren
  NeighborhoodsRoute: typeof NeighborhoodsRoute
  PartnersRoute: typeof PartnersRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhoods': {
      id: '/neighborhoods'
      path: '/neighborhoods'
      fullPath: '/neighborhoods'
      preLoaderRoute: typeof NeighborhoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/listings/$slug': {
      id: '/listings/$slug'
      path: '/$slug'
      fullPath: '/listings/$slug'
      preLoaderRoute: typeof ListingsSlugRouteImport
      parentRoute: typeof ListingsRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/impressions': {
      id: '/admin/impressions'
      path: '/impressions'
      fullPath: '/admin/impressions'
      preLoaderRoute: typeof AdminImpressionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings/': {
      id: '/admin/listings/'
      path: '/listings'
      fullPath: '/admin/listings/'
      preLoaderRoute: typeof AdminListingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings/new': {
      id: '/admin/listings/new'
      path: '/listings/new'
      fullPath: '/admin/listings/new'
      preLoaderRoute: typeof AdminListingsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings/$id': {
      id: '/admin/listings/$id'
      path: '/listings/$id'
      fullPath: '/admin/listings/$id'
      preLoaderRoute: typeof AdminListingsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/articles/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles/$id': {
      id: '/admin/articles/$id'
      path: '/articles/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AdminArticlesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminImpressionsRoute: typeof AdminImpressionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArticlesIdRoute: typeof AdminArticlesIdRoute
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminListingsIdRoute: typeof AdminListingsIdRoute
  AdminListingsNewRoute: typeof AdminListingsNewRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
  AdminListingsIndexRoute: typeof AdminListingsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminImpressionsRoute: AdminImpressionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArticlesIdRoute: AdminArticlesIdRoute,
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminListingsIdRoute: AdminListingsIdRoute,
  AdminListingsNewRoute: AdminListingsNewRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
  AdminListingsIndexRoute: AdminListingsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface ListingsRouteChildren {
  ListingsSlugRoute: typeof ListingsSlugRoute
}

const ListingsRouteChildren: ListingsRouteChildren = {
  ListingsSlugRoute: ListingsSlugRoute,
}

const ListingsRouteWithChildren = ListingsRoute._addFileChildren(
  ListingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ArticlesRoute: ArticlesRouteWithChildren,
  AuthRoute: AuthRoute,
  ListingsRoute: ListingsRouteWithChildren,
  NeighborhoodsRoute: NeighborhoodsRoute,
  PartnersRoute: PartnersRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
