INSERT INTO public.homepage_sections (section_key, section_type, position, enabled, draft_content, published_content, published_at)
VALUES
('hotels_hero', 'category_hub_hero', 100, true,
  '{"eyebrow":"Where to stay","heading":"San Diego Hotels","heading_accent":"where to stay.","subheading":"Beachfront resorts, downtown boutiques and historic stays — every property reviewed by our editors. Insider members save up to 40%.","hero_image_url":"https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1600&q=80","search_placeholder":"Search hotels, neighborhoods, amenities…","popular_chips":[{"label":"Beachfront","keyword":"beach"},{"label":"Downtown","keyword":"downtown"},{"label":"Boutique","keyword":"boutique"},{"label":"Family","keyword":"family"}],"stats":[{"value":"200+","label":"Hotels"},{"value":"40%","label":"Insider Save"},{"value":"$129","label":"Starting From"}],"insider_cta_title":"Save up to 40% with Insider","insider_cta_body":"Member-only rates, free upgrades and late checkout at participating hotels.","sponsor_active":false,"sponsor_name":"","sponsor_logo_url":"","sponsor_link_url":""}'::jsonb,
  '{"eyebrow":"Where to stay","heading":"San Diego Hotels","heading_accent":"where to stay.","subheading":"Beachfront resorts, downtown boutiques and historic stays — every property reviewed by our editors. Insider members save up to 40%.","hero_image_url":"https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1600&q=80","search_placeholder":"Search hotels, neighborhoods, amenities…","popular_chips":[{"label":"Beachfront","keyword":"beach"},{"label":"Downtown","keyword":"downtown"},{"label":"Boutique","keyword":"boutique"},{"label":"Family","keyword":"family"}],"stats":[{"value":"200+","label":"Hotels"},{"value":"40%","label":"Insider Save"},{"value":"$129","label":"Starting From"}],"insider_cta_title":"Save up to 40% with Insider","insider_cta_body":"Member-only rates, free upgrades and late checkout at participating hotels.","sponsor_active":false,"sponsor_name":"","sponsor_logo_url":"","sponsor_link_url":""}'::jsonb,
  now()),
('restaurants_hero', 'category_hub_hero', 101, true,
  '{"eyebrow":"Where to eat","heading":"San Diego Restaurants","heading_accent":"where locals eat.","subheading":"From Michelin-starred dining rooms to legendary taco shops — the restaurants locals actually eat at, ranked by what''s worth your time.","hero_image_url":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1600&q=80","search_placeholder":"Search restaurants, cuisines, neighborhoods…","popular_chips":[{"label":"Tacos","keyword":"taco"},{"label":"Waterfront","keyword":"waterfront"},{"label":"Michelin","keyword":"michelin"},{"label":"Brunch","keyword":"brunch"}],"stats":[{"value":"500+","label":"Restaurants"},{"value":"30","label":"Neighborhoods"},{"value":"$$","label":"Avg Price"}],"insider_cta_title":"Dine smarter with Insider","insider_cta_body":"Priority reservations, complimentary courses and chef''s-table access at top spots.","sponsor_active":false,"sponsor_name":"","sponsor_logo_url":"","sponsor_link_url":""}'::jsonb,
  '{"eyebrow":"Where to eat","heading":"San Diego Restaurants","heading_accent":"where locals eat.","subheading":"From Michelin-starred dining rooms to legendary taco shops — the restaurants locals actually eat at, ranked by what''s worth your time.","hero_image_url":"https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1600&q=80","search_placeholder":"Search restaurants, cuisines, neighborhoods…","popular_chips":[{"label":"Tacos","keyword":"taco"},{"label":"Waterfront","keyword":"waterfront"},{"label":"Michelin","keyword":"michelin"},{"label":"Brunch","keyword":"brunch"}],"stats":[{"value":"500+","label":"Restaurants"},{"value":"30","label":"Neighborhoods"},{"value":"$$","label":"Avg Price"}],"insider_cta_title":"Dine smarter with Insider","insider_cta_body":"Priority reservations, complimentary courses and chef''s-table access at top spots.","sponsor_active":false,"sponsor_name":"","sponsor_logo_url":"","sponsor_link_url":""}'::jsonb,
  now()),
('things-to-do_hero', 'category_hub_hero', 102, true,
  '{"eyebrow":"What to do","heading":"Things To Do in San Diego","heading_accent":"things to do.","subheading":"Iconic attractions, hidden coves, hands-on tours and one-of-a-kind experiences — the only San Diego itinerary you''ll need.","hero_image_url":"https://images.unsplash.com/photo-1612698093158-e07ac200d44e?w=1600&q=80","search_placeholder":"Search attractions, tours, beaches…","popular_chips":[{"label":"Beaches","keyword":"beach"},{"label":"Museums","keyword":"museum"},{"label":"Family","keyword":"family"},{"label":"Outdoor","keyword":"outdoor"}],"stats":[{"value":"1,200+","label":"Things To Do"},{"value":"70","label":"Miles of Coast"},{"value":"266","label":"Sunny Days"}],"insider_cta_title":"Skip the line with Insider","insider_cta_body":"Front-of-line passes, member discounts and exclusive tours at top attractions.","sponsor_active":false,"sponsor_name":"","sponsor_logo_url":"","sponsor_link_url":""}'::jsonb,
  '{"eyebrow":"What to do","heading":"Things To Do in San Diego","heading_accent":"things to do.","subheading":"Iconic attractions, hidden coves, hands-on tours and one-of-a-kind experiences — the only San Diego itinerary you''ll need.","hero_image_url":"https://images.unsplash.com/photo-1612698093158-e07ac200d44e?w=1600&q=80","search_placeholder":"Search attractions, tours, beaches…","popular_chips":[{"label":"Beaches","keyword":"beach"},{"label":"Museums","keyword":"museum"},{"label":"Family","keyword":"family"},{"label":"Outdoor","keyword":"outdoor"}],"stats":[{"value":"1,200+","label":"Things To Do"},{"value":"70","label":"Miles of Coast"},{"value":"266","label":"Sunny Days"}],"insider_cta_title":"Skip the line with Insider","insider_cta_body":"Front-of-line passes, member discounts and exclusive tours at top attractions.","sponsor_active":false,"sponsor_name":"","sponsor_logo_url":"","sponsor_link_url":""}'::jsonb,
  now()),
('shopping_hero', 'category_hub_hero', 103, true,
  '{"eyebrow":"Where to shop","heading":"San Diego Shopping","heading_accent":"where to shop.","subheading":"From La Jolla boutiques to North Park vintage and Liberty Station artisans — the shops locals send their visiting friends to.","hero_image_url":"https://images.unsplash.com/photo-1481437156560-3205f6a55735?w=1600&q=80","search_placeholder":"Search shops, boutiques, markets…","popular_chips":[{"label":"Boutiques","keyword":"boutique"},{"label":"Vintage","keyword":"vintage"},{"label":"Markets","keyword":"market"},{"label":"Outlets","keyword":"outlet"}],"stats":[{"value":"150+","label":"Shops"},{"value":"12","label":"Districts"},{"value":"Daily","label":"Markets"}],"insider_cta_title":"Shop smarter with Insider","insider_cta_body":"Member-only discounts and early access at participating boutiques and markets.","sponsor_active":false,"sponsor_name":"","sponsor_logo_url":"","sponsor_link_url":""}'::jsonb,
  '{"eyebrow":"Where to shop","heading":"San Diego Shopping","heading_accent":"where to shop.","subheading":"From La Jolla boutiques to North Park vintage and Liberty Station artisans — the shops locals send their visiting friends to.","hero_image_url":"https://images.unsplash.com/photo-1481437156560-3205f6a55735?w=1600&q=80","search_placeholder":"Search shops, boutiques, markets…","popular_chips":[{"label":"Boutiques","keyword":"boutique"},{"label":"Vintage","keyword":"vintage"},{"label":"Markets","keyword":"market"},{"label":"Outlets","keyword":"outlet"}],"stats":[{"value":"150+","label":"Shops"},{"value":"12","label":"Districts"},{"value":"Daily","label":"Markets"}],"insider_cta_title":"Shop smarter with Insider","insider_cta_body":"Member-only discounts and early access at participating boutiques and markets.","sponsor_active":false,"sponsor_name":"","sponsor_logo_url":"","sponsor_link_url":""}'::jsonb,
  now()),
('nightlife_hero', 'category_hub_hero', 104, true,
  '{"eyebrow":"After dark","heading":"San Diego Nightlife","heading_accent":"after dark.","subheading":"Rooftop sunsets in Little Italy, dive bars in Ocean Beach, late-night cocktails Downtown — the spots worth staying out for.","hero_image_url":"https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=1600&q=80","search_placeholder":"Search bars, clubs, lounges…","popular_chips":[{"label":"Rooftops","keyword":"rooftop"},{"label":"Cocktails","keyword":"cocktail"},{"label":"Live Music","keyword":"music"},{"label":"Dive Bars","keyword":"dive"}],"stats":[{"value":"120+","label":"Venues"},{"value":"Late","label":"Open Til 2am"},{"value":"$12","label":"Avg Cocktail"}],"insider_cta_title":"Skip the line with Insider","insider_cta_body":"VIP entry, complimentary drinks and table reservations at top venues.","sponsor_active":false,"sponsor_name":"","sponsor_logo_url":"","sponsor_link_url":""}'::jsonb,
  '{"eyebrow":"After dark","heading":"San Diego Nightlife","heading_accent":"after dark.","subheading":"Rooftop sunsets in Little Italy, dive bars in Ocean Beach, late-night cocktails Downtown — the spots worth staying out for.","hero_image_url":"https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=1600&q=80","search_placeholder":"Search bars, clubs, lounges…","popular_chips":[{"label":"Rooftops","keyword":"rooftop"},{"label":"Cocktails","keyword":"cocktail"},{"label":"Live Music","keyword":"music"},{"label":"Dive Bars","keyword":"dive"}],"stats":[{"value":"120+","label":"Venues"},{"value":"Late","label":"Open Til 2am"},{"value":"$12","label":"Avg Cocktail"}],"insider_cta_title":"Skip the line with Insider","insider_cta_body":"VIP entry, complimentary drinks and table reservations at top venues.","sponsor_active":false,"sponsor_name":"","sponsor_logo_url":"","sponsor_link_url":""}'::jsonb,
  now())
ON CONFLICT (section_key) DO NOTHING;